---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer-sa
  namespace: default  # Change this if your Vault is elsewhere
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unsealer-role
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    # Needed to find the IPs of the Vault replicas
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    # Narrowing this down to 'get' for security. 
    # The script doesn't need to 'list' all secrets, just fetch yours.
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer-rolebinding
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: vault-unsealer-sa
    namespace: default
roleRef:
  kind: Role
  name: vault-unsealer-role
  apiGroup: rbac.authorization.k8s.io



kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "secrets", "pods" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-autounseal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-autounseal.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-autounseal.fullname" . }}
