---
{{- $basename := include "vault-autounseal.fullname" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-role" $basename }}
  namespace: {{ default .Release.Namespace .Values.namespace.nameOverride }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    # Needed to find the IPs of the Vault replicas
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    # Narrowing this down to 'get' for security. 
    # The script doesn't need to 'list' all secrets, just fetch yours.
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-rolebinding" $basename }}
  namespace: {{ default .Release.Namespace .Values.namespace.nameOverride }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-autounseal.serviceAccountName" . }}
    namespace: {{ default .Release.Namespace .Values.namespace.nameOverride }}
roleRef:
  kind: Role
  name: {{ printf "%s-role" $basename }}
  apiGroup: rbac.authorization.k8s.io
---
